### PR TITLE
Rewrite asset-pipeline-spring-boot servlets as standalone servlets

### PR DESCRIPTION
**Pull request by augustl**
Referring to the discussion in issue #67.

This pull request contains two commits.

One commit creates a new project, asset-pipeline-servlet. It is a port of the servlets from asset-pipeline-spring-boot, that uses two interfaces (a resource repo and a resource) to make the resource fetching pluggable. Integration tests were also added, in the form of a JUnit test that spawns a full jetty servlet and mounts up the servlets from asset-pipeline-servlet, and uses Apache's HTTP lib to assert that it works.

The other commit rewrites the servlets in asset-pipeline-spring-boot to make use of the new servlets in asset-pipeline-servlet, and implements the two resource interfaces to use spring's WebApplicationContext to fetch resources.

Some notes:

* Manual verification is required to check that the servlets in asset-pipeline-spring-boot still works. I've never usec spring-boot so it would make sense if someone familiar with spring-boot does that checking.
* Please let me know if the integration tests spawning up jetty is overkill :)
* If you want me to, I can stick around and act as the maintainer of the asset-pipeline-servlet module, responding to issues about it etc.

### CODE REVIEW

**Comment by davydotcom** [comment]
Awesome! I'll take a look tomorrow

**Comment by augustl** [comment]
Ping!

Getting tired of using the "default" servlet to serve static assets, and having to tell my beta testers to manually clear the cache of the browser when I release a new version :)

**Comment by augustl** [comment]
Thanks!

I'll start integrating this into my project so it's actually tested in the real world too :)

**Comment by augustl** [comment]
Tested the dev filter, it works fine.

Do you know when the next release will be?

**Comment by davydotcom** [comment]
This week I'm just trying to get a few other known issues worked out and work has been busy

**Comment by augustl** [comment]
Allright, thanks for the info. I'll deploy a snapshot to our own repo in the meantime :)

**Comment by davydotcom** [comment]
Just a heads up on this one I refactored the core filter to use `AssetPipelineResponseBuilder` this class handles generating the appropriate headers and ETags and `Last-Modified` in a way that works for more than just servlet based filters (cleaner and more generic).

**Pull request merged**
