### PR TITLE
Expose org.graalvm.sdk:graal-sdk dependency as compileOnlyApi

### PR DESCRIPTION
**Pull request by jamesfredley**
This saves having to add it to every Grails 7 application

### CODE REVIEW

**Comment by codeconsole** [comment]
That dependency is not required.  I am running a Grails 7 app and Asset Pipeline 5.0.1 and do not need it.

**Comment by davydotcom** [comment]
This is only needed for compile time or development runtime. We wanted to explicitly exclude it from getting injected into the war/jar because its not required for production war builds.

**Comment by jamesfredley** [comment]
@codeconsole's Grails 7 [application ](https://github.com/codeconsole/website/blob/7.0.0-SNAPSHOT/build.gradle) doesn't need this dependency because he removed 

`implementation("com.bertramlabs.plugins:asset-pipeline-gradle:5.0.1")` from buildSrc/build.gradle, he actually fully consolidated buildSrc and settings.gradle into build.gradle, but that one line is the source of this error.

And has it defined in one location in build.gradle:

```
plugins {
     id "com.bertramlabs.asset-pipeline" version "5.0.1"
}
```

We had planned to go that direction for `forge create-app` and `grails-shell create-app`, so if we don't think this will pop up in another way, we can close it.

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-forge/pull/395

**Comment by davydotcom** [comment]
so this issue is purely related to the gradle side?

**Comment by davydotcom** [comment]
you do need it in grails run-app or dev but not in the final jar or war. need a way to inject this dependency but NOT package it in the war/jar

**Comment by mkobel** [comment]
We have a similar, probably related, issue using spring boot .

A possible workaround is adding graalvm to `assets` in `build.gradle`:

```
dependecies {
    [..]
    assets 'org.graalvm.polyglot:js:24.1.1' // avoid java.lang.ClassNotFoundException: org.graalvm.polyglot.Value when calling js file
    assets 'org.graalvm.polyglot:polyglot:24.1.1' // avoid java.lang.ClassNotFoundException: org.graalvm.polyglot.Value when 
calling js file
    [..]
}
```

Using `assets 'org.graalvm.sdk:graal-sdk:24.1.1'` as workaround works too.

**Comment by fernando88to** [comment]
> We have a similar, probably related, issue using spring boot .
> 
> A possible workaround is adding graalvm to `implementation` in `build.gradle`:
> 
> ```
> dependecies {
>     [..]
>     implementation 'org.graalvm.polyglot:js:24.1.1' // avoid java.lang.ClassNotFoundException: org.graalvm.polyglot.Value when calling js file
>     implementation 'org.graalvm.polyglot:polyglot:24.1.1' // avoid java.lang.ClassNotFoundException: org.graalvm.polyglot.Value when 
> calling js file
>     [..]
> }
> ```
> 
> Using `implementation 'org.graalvm.sdk:graal-sdk:24.1.1'` as workaround works too.

With jdk 17 this solution above worked, but in my case I am using jdk 11 which is not compatible.



 org/graalvm/polyglot/Value has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by jamesfredley** [comment]
This will end up being a somewhat frequent occurrence for those upgrading to Grails 7, that had been loading `asset-pipeline-gradle` in `buildSrc` vs the new way in `plugins{}` by id only.

transitioning from `buildSrc/build.gradle`:
`implementation("com.bertramlabs.plugins:asset-pipeline-gradle:5.0.1")`

to `build.gradle` only:
```
plugins {
     id "com.bertramlabs.asset-pipeline" version "5.0.1"
}
```

**Comment by jdaugherty** [comment]
@davydotcom Do you have a suggestion on how to make this available only during development?  I'm assuming this is a gradle plugin change for grails?

**Comment by jamesfredley** [comment]
Updated PR to use `compileOnlyApi` Gradle configuration instead of `api`.

https://docs.gradle.org/current/userguide/java_library_plugin.html
image

**Comment by codeconsole** [comment]
I am not sure if `compileOnlyApi` would fix your issue because it sounds like it is happening at development runtime.  

I don't recommend any change if it is only for people who are loading the plugin incorrectly. if it works in a `plugins {}` block, then that should be the requirement.

**Comment by jamesfredley** [comment]
`compileOnlyApi` did not address the development runtime issue.  

More details are captured on https://github.com/grails/grails-core/issues/13913 including the workaround we used for a number of Grails projects and on [start.grails.org](start.grails.org) for Grails 6.2.2 and 7.0.0-SNAPSHOT.

https://github.com/grails/grails-core/issues/13913#issuecomment-2532078876 includes more details on the root issue, although all details of the root cause have not been tracked down.

**Comment by codeconsole** [comment]
@av-m @jamesfredley is this a windows only or a jdk 17 issue? why do I not get this exception in development mode without these dependencies with jdk 21 on osx?

**Comment by fernando88to** [comment]
It also happens with JDK 11.

**Comment by codeconsole** [comment]
Has anyone identified what exactly is being excused that is actually causing these exceptions?

Is there a chance the class doesn't even need to be loaded in the first place??
```
java.lang.ClassNotFoundException: org.graalvm.polyglot.Context
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
```

**Comment by codeconsole** [comment]
https://github.com/bertramdev/asset-pipeline/pull/370

**Pull request merged**
