### PR TITLE
Service to core

### PR DESCRIPTION
**Pull request by rgoldberg**
moved non-Grails instance methods from asset-pipeline-grails AssetProcessorService to static methods in new asset-pipeline-core AssetPaths
This is branched from the simple-cleanup PR, so please merge that first to isolate commits specific to this PR

### CODE REVIEW

**Comment by davydotcom** [comment]
most non service based stuff has a home already in AssetPipeline.groovy and AssetHelper.groovy

**Comment by rgoldberg** [comment]
Where do you want me to put the methods?  Or can you just merge and move them to whatever class you prefer?

**Comment by rgoldberg** [comment]
Just pinging to find out what I can do to get these cleanups merged.

**Comment by davydotcom** [comment]
probably next week i have to figure out where a few things go and have a feature update im trying to get out

**Pull request closed without merging**
