### PR TITLE
Adding support for If-Modified-Since header and also using GMT

### PR DESCRIPTION
**Pull request by ctoestreich**

### CODE REVIEW

**Comment by ctoestreich** [comment]
```
curl -k -I -H "If-Modified-Since: Tue, 29 Sep 2015 23:16:58 GMT" http://localhost:9292/bcp-assets/application.js
HTTP/1.1 304 Not Modified
Server: Apache-Coyote/1.1
Last-Modified: Tue, 29 Sep 2015 22:38:42 GMT
ETag: application-530037d5fd5cc15d54d70b866376add9.js
Vary: Accept-Encoding
Cache-Control: public, max-age=31536000
Date: Tue, 29 Sep 2015 22:45:05 GMT
```

**Comment by davydotcom** [comment]
has some conflicts. can you fix those and ill get it merged?

**Comment by davydotcom** [comment]
woohoo that was a doozy of a merge NOTE: need to move most of htis logic to the response builder in core

**Comment by ctoestreich** [comment]
You're welcome... Making life hard for @davydotcom since 2015.

**Comment by davydotcom** [comment]
hehe was my fault forgot to merge before i refactored the filter dramatically

**Pull request merged**
