### PR TITLE
Prevent duplicate javascript includes

### PR DESCRIPTION
**Pull request by dustindclark**
If jquery is included, extended, and then included again (which is the case when multiple script files depend on jquery), the jquery extension is blown away.  This fix eliminates the problem by preventing duplicate script includes within the same request.

### CODE REVIEW

**Comment by davydotcom** [comment]
You need to  clarify why would be doing this. require directive are used to bundle things together. Sure this would stop a duplicate include in a debug mode scenario but not necessarily war mode.

**Comment by dustindclark** [comment]
The bug is present in both run and war modes, but I'm still working on the war fix.
Example here: https://github.com/dustindclark/asset-pipeline-dup-js

This renders the following markup:

```html
<html>
	<head>
		<title>Welcome to Grails</title>
		<script src="/asset-pipeline-dup-js/assets/jquery/jquery-1.11.1.js?compile=false" type="text/javascript"/>
		<script src="/asset-pipeline-dup-js/assets/jquery.js?compile=false" type="text/javascript"/>
		<script src="/asset-pipeline-dup-js/assets/jquery.simplemodal-1.4.4.js?compile=false" type="text/javascript"/>
		<script src="/asset-pipeline-dup-js/assets/modal.js?compile=false" type="text/javascript"/>
		<script src="/asset-pipeline-dup-js/assets/jquery/jquery-1.11.1.js?compile=false" type="text/javascript"/>
		<script src="/asset-pipeline-dup-js/assets/jquery.js?compile=false" type="text/javascript"/>
		<script src="/asset-pipeline-dup-js/assets/application.js?compile=false" type="text/javascript"/>
	</head>
	<body>
		<script>
            $.modal("<div><h1>SimpleModal</h1></div>", {});
        </script>
	</body>
</html>
```

And ultimately results in this message (without my fix applied):

```
TypeError: undefined is not a function (evaluating '$.modal("<div><h1>SimpleModal</h1></div>", {})')
```

The duplicate jQuery include wipes out any extensions defined above it (in this case, simple modal).

**Comment by davydotcom** [comment]
You should not be requiring jQuery in 2 separate asset:javascript includes. Only require it from one bundle. This fix would fix it for dev mode but you’d get bitten in war mode due to the bundling happening on compile. The bundling has no idea how you include those files so its going to be a problem no matter what in this manner.
--
David Estes

On January 31, 2015 at 3:40:47 PM, Dustin Clark (notifications@github.com) wrote:

The bug is present in both run and war modes, but I'm still working on the war fix.
Example here: https://github.com/dustindclark/asset-pipeline-dup-js

This renders the following markup:

<html>
    <head>
        <title>Welcome to Grails</title>
        <script src="/asset-pipeline-dup-js/assets/jquery/jquery-1.11.1.js?compile=false" type="text/javascript"/>
        <script src="/asset-pipeline-dup-js/assets/jquery.js?compile=false" type="text/javascript"/>
        <script src="/asset-pipeline-dup-js/assets/jquery.simplemodal-1.4.4.js?compile=false" type="text/javascript"/>
        <script src="/asset-pipeline-dup-js/assets/modal.js?compile=false" type="text/javascript"/>
        <script src="/asset-pipeline-dup-js/assets/jquery/jquery-1.11.1.js?compile=false" type="text/javascript"/>
        <script src="/asset-pipeline-dup-js/assets/jquery.js?compile=false" type="text/javascript"/>
        <script src="/asset-pipeline-dup-js/assets/application.js?compile=false" type="text/javascript"/>
    </head>
    <body>
        <script>
            $.modal("<div><h1>SimpleModal</h1></div>", {});
        </script>
    </body>
</html>
And ultimately results in this message (without my fix applied):

TypeError: undefined is not a function (evaluating '$.modal("<div><h1>SimpleModal</h1></div>", {})')

The duplicate jQuery include wipes out any extensions defined above it (in this case, simple modal).

**Comment by dustindclark** [comment]
I see what you're saying...this can't work in war mode unless you knew each combination of js files at build time.  And you obviously wouldn't want it to work in run mode if it's going to break in war mode.  I guess the minimalistic approach of only including the js that you need to run a page will not work.  So either use a gigantic js bundle for the entire app, or create different bundle combinations in individual manifest files.  Got it.

**Pull request closed without merging**
