### PR TITLE
Adding Last-Modified header to plugin and core

### PR DESCRIPTION
**Pull request by ctoestreich**

### CODE REVIEW

**Comment by ctoestreich** [comment]
This needs the new core to pass.

**Comment by ctoestreich** [comment]
@davydotcom Just touching base on status of core update/deploy and plugin release.

**Comment by davydotcom** [comment]
got a few bug fixes with relative paths coming in want to push into this release as well. probably tomorrow release cool? if not i can push yours out right now

**Comment by ctoestreich** [comment]
If you can push that would be awesome, but not at the expense of having to monkey patch any new code out/in.

**Comment by ctoestreich** [comment]
I am heading to meeting with Akamai now to discuss why they can't just use E-Tags instead of Last-Modified, but their docs basically say "no last-modified, no cache (304s)"

**Comment by davydotcom** [comment]
Gotya. Why do so many CDNs suck so bad ;)

**Comment by davydotcom** [comment]
Fyi in the process of deploying 2.5.2 now

**Comment by ctoestreich** [comment]
We pay A LOT for that suck.  $$$$

**Comment by ctoestreich** [comment]
:+1:

**Comment by davydotcom** [comment]
Im working on a new one with better digest support built in ;)

**Comment by davydotcom** [comment]
2.5.2 released

**Comment by ctoestreich** [comment]
I think we broke grails.org ;P  

https://grails.org/plugin/asset-pipeline

**Comment by davydotcom** [comment]
well thats awesome! ;) lol

**Comment by davydotcom** [comment]
let me know on 2.5.2 if it goes ok for you i see some failing tests showed up from some commits from another PR I'm checking them now. It looks like its just the test needs adjusted though

**Pull request merged**
