### PR TITLE
should use Slf4j (or another wrapper library) in case the containing app uses Logback/Log4j2/etc.

### PR DESCRIPTION
**Pull request by burtbeckwith**

### CODE REVIEW

**Comment by davydotcom** [comment]
thanks, didn't know grails could use logback and others thought it was just log4j

**Comment by burtbeckwith** [comment]
There's a plugin for that (tm) http://grails.org/plugin/logback

**Comment by genuinefafa** [comment]
@burtbeckwith you include many non-issue-related changes. What's the _important_ difference?

**Comment by burtbeckwith** [comment]
There are two commits. The bigger one is trivial cleanup stuff, and the smaller one is just the Log4j -> Slf4j switch

**Comment by genuinefafa** [comment]
when you are right... you really are... cheers! :wine_glass:

**Pull request merged**
